name: glidertools-conda
channels:
  - conda-forge
  - defaults
dependencies:
        - python=3.7
        - matplotlib
        - seawater
        - tqdm
        - scipy
        - scikit-learn
        - numpy 
        - xarray
        - pandas
        - astral
        - netCDF4
        - numexpr
        - pip
